# Generated by Django 4.2.16 on 2024-11-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingListItem',
        ),
    ]
