# Generated by Django 3.2.16 on 2024-11-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('г', 'Грамм'), ('кг', 'Килограмм'), ('мг', 'Миллиграмм'), ('л', 'Литр'), ('мл', 'Миллилитр')], max_length=2, verbose_name='Единица измерения'),
        ),
    ]
