# Generated by Django 4.2.16 on 2024-12-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_favorite_options_alter_favorite_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
