# Generated by Django 4.2.16 on 2024-12-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, max_length=1024, null=True, upload_to='users/images/'),
        ),
    ]
