# Generated by Django 4.2.16 on 2024-12-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0003_alter_shoppinglist_recipes_alter_shoppinglist_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'verbose_name': 'Список покупок', 'verbose_name_plural': 'Списки покупок'},
        ),
    ]
