# Generated by Django 4.2.16 on 2024-12-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('following', '0003_alter_follow_following_alter_follow_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
    ]
