# Generated by Django 4.2.16 on 2024-11-30 12:23

import recipes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipeingredient_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[recipes.validators.validate_amount], verbose_name='Количество'),
        ),
    ]
