# Generated by Django 4.2.16 on 2024-12-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('г', 'Грамм'), ('кг', 'Килограмм'), ('мг', 'Миллиграмм'), ('л', 'Литр'), ('мл', 'Миллилитр'), ('шт.', 'Штука'), ('ч. л.', 'Чайная ложка'), ('ст. л.', 'Столовая ложка'), ('капля', 'Капля'), ('кусок', 'Кусок'), ('банка', 'Банка'), ('стакан', 'Стакан'), ('щепотка', 'Щепотка'), ('горсть', 'Горсть')], max_length=10, verbose_name='Единица измерения'),
        ),
    ]
